server:
  port: 9002

spring:
  application:
    name: lagou-cloud-gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: lagou-service-code
          uri: lb://lagou-service-code
          predicates:
            - Path=/code/**
        - id: lagou-service-email
          uri: lb://lagou-service-email
          predicates:
            - Path=/email/**
        - id: lagou-service-user
          uri: lb://lagou-service-user
          predicates:
            - Path=/user/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

ipflash:
  count: 100
  time: 1
  
