server:
  port: 9002

spring:
  application:
  name: lagou-cloud-gateway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: lagou-service-code
          uri: lb://lagou-service-code
          predicates:
            - Path=/code/**
        - id: lagou-service-email
          uri: lb://lagou-service-email
          predicates:
            - Path=/email/**
        - id: lagou-service-user
          uri: lb://lagou-service-user
          predicates:
            - Path=/user/**
